# Generated by Django 4.2.1 on 2023-06-14 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('gender', models.CharField(choices=[('ME', 'Masculino'), ('FE', 'Feminino')], max_length=2)),
            ],
        ),
    ]
