# Generated by Django 4.2.1 on 2023-06-22 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epidemiological', '0002_gender_alter_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gender',
            name='name',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino')], max_length=255),
        ),
    ]
