# Generated by Django 4.2.1 on 2023-06-15 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RiskRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('Azul', 'Não Urgente'), ('Verde', 'Pouco Urgente'), ('Amarelo', 'Urgente'), ('Laranja', 'Muito Urgente'), ('Vermelho', 'Emergente'), ('Outros', 'Outros')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='typeOfOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('ACIDENTE E VIOLENCIA', 'ACIDENTE E VIOLENCIA'), ('CLINICO', 'CLINICO'), ('N.PREENC', 'N.PREENC'), ('OBSTÉTRICO', 'OBSTÉTRICO'), ('OUTROS', 'OUTROS'), ('PSIQUIATRICO', 'PSIQUIATRICO')], max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfTrafficAccident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('Atropelamento', 'Atropelamento'), ('Capotamento', 'Capotamento'), ('Colisão', 'Colisão'), ('Ignorado', 'Ignorado'), ('N.Preenc', 'N.Preenc'), ('Outros', 'Outros'), ('Queda Bicicleta', 'Queda Bicicleta'), ('Queda Moto', 'Queda Moto')], max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('Avançada', 'Avançada'), ('Intermediaria', 'Intermediaria'), ('Basica', 'Basica')], max_length=100, null=True)),
            ],
        ),
    ]
