# Generated by Django 4.2.1 on 2023-06-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskrating',
            name='rating',
            field=models.CharField(choices=[('Não Urgente', 'Azul'), ('Pouco Urgente', 'Verde'), ('Urgente', 'Amarelo'), ('Muito Urgente', 'Laranja'), ('Emergente', 'Vermelho'), ('Outros', 'Outros')], max_length=100),
        ),
        migrations.AlterField(
            model_name='typeofoccurrence',
            name='name',
            field=models.CharField(blank=True, choices=[('Acidente e Violencia', 'Acidente e Violencia'), ('Clinico', 'Clinico'), ('Obstétrico', 'Obstétrico'), ('Outros', 'Outros'), ('Psiquiatrico', 'Psiquiatrico')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='typeoftrafficaccident',
            name='name',
            field=models.CharField(blank=True, choices=[('Atropelamento', 'Atropelamento'), ('Capotamento', 'Capotamento'), ('Colisão', 'Colisão'), ('Outros', 'Outros'), ('Queda Bicicleta', 'Queda Bicicleta'), ('Queda Moto', 'Queda Moto')], max_length=100, null=True),
        ),
    ]
