# Generated by Django 4.2.1 on 2023-06-18 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_riskrating_rating_alter_typeofoccurrence_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unittype',
            name='name',
            field=models.CharField(blank=True, choices=[('Avançada', 'Avançada'), ('Intermediaria', 'Intermediaria'), ('Basica', 'Basica')], max_length=100, null=True, unique=True),
        ),
    ]
