# Generated by Django 4.2.1 on 2023-06-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_alter_unittype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskrating',
            name='rating',
            field=models.CharField(choices=[('Não Urgente', 'Azul'), ('Pouco Urgente', 'Verde'), ('Urgente', 'Amarelo'), ('Muito Urgente', 'Laranja'), ('Emergente', 'Vermelho'), ('Outros', 'Outros'), ('------', '------')], default='------', max_length=100, unique=True),
        ),
    ]
