# Generated by Django 4.2.1 on 2023-06-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_alter_typeofoccurrence_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskrating',
            name='rating',
            field=models.CharField(choices=[('Não Urgente', 'Azul'), ('Pouco Urgente', 'Verde'), ('Urgente', 'Amarelo'), ('Muito Urgente', 'Laranja'), ('Emergente', 'Vermelho'), ('Outros', 'Outros')], max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='typeofoccurrence',
            name='name',
            field=models.CharField(choices=[('Acidente e Violencia', 'Acidente e Violência'), ('Clinico', 'Clinico'), ('Obstétrico', 'Obstétrico'), ('Psiquiatrico', 'Psiquiatrico'), ('Outros', 'Outros')], max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='typeoftrafficaccident',
            name='name',
            field=models.CharField(choices=[('Atropelamento', 'Atropelamento'), ('Capotamento', 'Capotamento'), ('Colisão', 'Colisão'), ('Queda Bicicleta', 'Queda Bicicleta'), ('Queda Moto', 'Queda Moto'), ('Outros', 'Outros')], max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='unittype',
            name='name',
            field=models.CharField(choices=[('Avançada', 'Avançada'), ('Intermediaria', 'Intermediaria'), ('Basica', 'Basica')], default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
