# Generated by Django 4.2.1 on 2023-06-22 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_alter_riskrating_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskrating',
            name='rating',
            field=models.CharField(choices=[('Não Urgente', 'Azul'), ('Pouco Urgente', 'Verde'), ('Urgente', 'Amarelo'), ('Muito Urgente', 'Laranja'), ('Emergente', 'Vermelho'), ('Outros', 'Outros')], max_length=100, unique=True),
        ),
    ]
