# Generated by Django 4.2.1 on 2023-06-22 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_alter_riskrating_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskrating',
            name='rating',
            field=models.CharField(choices=[('Azul', 'Não Urgente'), ('Verde', 'Pouco Urgente'), ('Amarelo', 'Urgente'), ('Laranja', 'Muito Urgente'), ('Vermelho', 'Emergente'), ('Outros', 'Outros')], max_length=100, unique=True),
        ),
    ]
