# Generated by Django 4.2.1 on 2023-06-22 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_alter_riskrating_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unittype',
            name='name',
            field=models.CharField(choices=[('------', '------'), ('Avançada', 'Avançada'), ('Intermediária', 'Intermediária'), ('Básica', 'Básica')], max_length=100, unique=True),
        ),
    ]
